name: gprof_nn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - h5py
  - pyproj
  - pyresample
  - cudatoolkit=11.3
  - pytorch
  - torchaudio
  - torchvision
  - tensorboard
prefix: /home/simon/.conda/envs/gprof_nn
